spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sammu@1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
